FROM python:3.10-slim
RUN pip install --no-cache-dir --progress-bar off flask
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  sample_app.py /home/myapp/
EXPOSE 9999
CMD python /home/myapp/sample_app.py
